name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou la branche que vous utilisez

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'  

    - name: Install dependencies
      run: npm install

    - name: Set up .env
      env:
        API_KEY: ${{ secrets.API_KEY }}  
      run: |
        echo "API_KEY=$API_KEY" >> .env

    - name: Start Server
      run: |
        npm start &  # Démarrer le serveur en arrière-plan
        sleep 5  # Attendre un petit peu pour que le serveur démarre

   - name: Deploy to GitHub Pages
  uses: JamesIves/github-pages-deploy-action@v4
  with:
    branch: gh-pages 
    folder: .
    token: ${{ secrets.DEPLOY_TOKEN }}
    clean: true
    force: true
